project:
  type: website

website:
  title: "ARMSNBL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - expression.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



